<?php

namespace AppBundle\Repository;

use BartB\FilterSorterBundle\Repository\AbstractEntitySpecificationAwareRepository;


/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends AbstractEntitySpecificationAwareRepository
{
}
